name: Deploy to aapanel

on: 
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Deploy Demo
    runs-on: ubuntu-latest
    setps:
      -name: SSH Remote
        uses: fifsky/ssh-action@master
        with:
          host: ${{ SSH_HOST }}
          user: ${{ SSH_USER }}
          password: ${{ SSH_PASSWORD }}
          port: ${{ SSH_PORT }}
          command: cd ../../www/wwwroot/emris && git pull origin main && npm install && npm run build && pm2 restart emris