name: Deploy Demo

on: 
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Deploy Demo
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote
        uses: fifsky/ssh-action@mast
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          command: cd ../../www/wwwroot/emris && git pull origin main && npm install && npm run build && pm2 restart emris